# Generated by Django 5.2.6 on 2026-05-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_construcao', 'Em Construção'), ('entregue', 'Entregue')], default='planejamento', max_length=20, verbose_name='Status')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empreendimentos', to='incorporadora.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocos', to='incorporadora.empreendimento', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['empreendimento', 'nome'],
                'unique_together': {('empreendimento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('tipologia', models.CharField(blank=True, max_length=100, verbose_name='Tipologia')),
                ('area_privativa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Privativa (m²)')),
                ('area_privativa_acessoria', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Priv. Acessória (m²)')),
                ('area_comum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Comum (m²)')),
                ('fracao_ideal', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Fração Ideal')),
                ('valor_tabela', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Tabela (R$)')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('permuta', 'Permuta')], default='disponivel', max_length=20, verbose_name='Status')),
                ('descricao1', models.CharField(blank=True, max_length=255, verbose_name='Descrição 1')),
                ('descricao2', models.CharField(blank=True, max_length=255, verbose_name='Descrição 2')),
                ('descricao3', models.CharField(blank=True, max_length=255, verbose_name='Descrição 3')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='incorporadora.bloco', verbose_name='Bloco')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['bloco', 'codigo'],
                'unique_together': {('bloco', 'codigo')},
            },
        ),
    ]
