# Generated by Django 5.2.6 on 2026-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0002_empreendimento_bloco_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='tipo',
            field=models.CharField(choices=[('apartamento', 'Apartamento'), ('garagem', 'Garagem'), ('hobby_box', 'Hobby Box'), ('sala', 'Sala'), ('loja', 'Loja')], default='apartamento', max_length=20, verbose_name='Tipo'),
        ),
    ]
