# Generated by Django 5.2.6 on 2026-05-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0004_unidade_codigo_to_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['bloco', 'numero'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unidade',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
    ]
