# Generated by Django 5.2.6 on 2026-05-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0006_unidade_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='unidade_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculadas', to='incorporadora.unidade', verbose_name='Unidade Principal'),
        ),
    ]
