# Generated by Django 5.2.6 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0007_unidade_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='numeros_adicionais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Números Adicionais'),
        ),
    ]
