# Generated by Django 5.2.6 on 2026-05-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0008_numeros_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='pagina',
            field=models.PositiveIntegerField(default=1, verbose_name='Página'),
        ),
        migrations.CreateModel(
            name='TabelaVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('modalidade', models.CharField(choices=[('bancaria', 'Bancária'), ('direta', 'Direta'), ('outra', 'Outra')], default='bancaria', max_length=20, verbose_name='Modalidade')),
                ('cub_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CUB de Referência')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas', to='incorporadora.empreendimento', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Tabela de Vendas',
                'verbose_name_plural': 'Tabelas de Vendas',
                'ordering': ['-data_referencia', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SeriePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('indice', models.CharField(choices=[('cub', 'CUB'), ('igpm', 'IGPM'), ('fixo', 'Fixo')], default='cub', max_length=10, verbose_name='Índice de Reajuste')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='incorporadora.tabelavendas', verbose_name='Tabela')),
            ],
            options={
                'verbose_name': 'Série de Pagamento',
                'verbose_name_plural': 'Séries de Pagamento',
                'ordering': ['tabela', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ItemTabelaVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('permuta', 'Permuta'), ('contrato', 'Contrato'), ('em_negociacao', 'Em Negociação'), ('reserva', 'Reserva'), ('proprio', 'Próprio')], default='disponivel', max_length=20, verbose_name='Status')),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor de Venda (R$)')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_tabela', to='incorporadora.unidade', verbose_name='Unidade')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='incorporadora.tabelavendas', verbose_name='Tabela')),
            ],
            options={
                'verbose_name': 'Item de Tabela de Vendas',
                'verbose_name_plural': 'Itens de Tabela de Vendas',
                'ordering': ['unidade__bloco__nome', 'unidade__pagina', 'unidade__ordem', 'unidade__numero'],
                'unique_together': {('tabela', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='ValorSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor por Parcela (R$)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='incorporadora.itemtabelavendas', verbose_name='Item')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='incorporadora.seriepagamento', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Valor de Série',
                'verbose_name_plural': 'Valores de Série',
                'unique_together': {('item', 'serie')},
            },
        ),
    ]
