# Generated by Django 5.2.6 on 2026-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0009_unidade_pagina_tabelavendas_seriepagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelavendas',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim de Vigência'),
        ),
        migrations.AddField(
            model_name='tabelavendas',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início de Vigência'),
        ),
    ]
