# Generated by Django 5.2.6 on 2026-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0010_tabelavendas_data_fim_tabelavendas_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriepagamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='seriepagamento',
            name='periodicidade',
            field=models.CharField(choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='unico', max_length=20, verbose_name='Periodicidade'),
        ),
        migrations.AddField(
            model_name='seriepagamento',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Primeiro Vencimento'),
        ),
        migrations.AddField(
            model_name='seriepagamento',
            name='tipo',
            field=models.CharField(choices=[('ato', 'Ato'), ('parcela', 'Parcela'), ('reforco', 'Reforço'), ('chaves', 'Chaves'), ('financiamento', 'Financiamento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo'),
        ),
    ]
