# Generated by Django 5.2.6 on 2026-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0011_seriepagamento_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriepagamento',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Percentual do valor de venda da unidade para esta série. Ex: 20 = 20%', max_digits=6, null=True, verbose_name='Percentual do Valor (%)'),
        ),
    ]
