# Generated by Django 5.2.6 on 2026-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0012_seriepagamento_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('permuta', 'Permuta'), ('bloqueado', 'Bloqueado')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
    ]
