# Generated by Django 5.2.6 on 2026-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0013_add_bloqueado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='perc_permuta',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Fração do valor/área destinada à permuta (ex: 0.12826). 0 = sem permuta parcial.', max_digits=8, verbose_name='% Permuta'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('permuta', 'Permuta'), ('bloqueado', 'Bloqueado'), ('qa', 'QA')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
    ]
