# Generated by Django 5.2.6 on 2026-05-29 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0014_add_qa_status_perc_permuta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cliente_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='E-mail do Cliente'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tabela_cv', 'Tabela CV (situação + valor)'), ('unidades', 'Unidades (dados completos)'), ('vinculos', 'Vínculos (garagens/HBs)'), ('atualizacao_mensal', 'Atualização Mensal'), ('vendas', 'Vendas (cliente/imobiliária)')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Registros')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='incorporadora.empreendimento', verbose_name='Empreendimento')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Importação',
                'verbose_name_plural': 'Logs de Importação',
                'ordering': ['-importado_em'],
            },
        ),
    ]
