# Generated by Django 5.2.6 on 2026-05-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0015_add_importlog_cliente_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='area_comum',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Área Comum (m²)'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='area_privativa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Área Privativa (m²)'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='area_privativa_acessoria',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Área Priv. Acessória (m²)'),
        ),
    ]
