# Generated by Django 5.2.6 on 2026-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0016_area_decimal_places_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'ordering': ['empreendimento', 'ordem', 'nome'], 'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
        migrations.AddField(
            model_name='bloco',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
