# Generated by Django 6.0.6 on 2026-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudo',
            name='assistencia_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='capital_proprio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='estudo',
            name='capital_proprio_ck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudo',
            name='corretagem_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='despesas_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='financ_prod_carencia',
            field=models.IntegerField(default=0, help_text='Carência em meses'),
        ),
        migrations.AddField(
            model_name='estudo',
            name='financ_prod_perc_construido',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% construído para liberar', max_digits=8),
        ),
        migrations.AddField(
            model_name='estudo',
            name='financ_prod_perc_financiamento',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% do custo financiado', max_digits=8),
        ),
        migrations.AddField(
            model_name='estudo',
            name='financ_prod_perc_vendido',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% vendido para liberar', max_digits=8),
        ),
        migrations.AddField(
            model_name='estudo',
            name='financ_prod_qtde_parcelas',
            field=models.IntegerField(default=0, help_text='Qtde de parcelas'),
        ),
        migrations.AddField(
            model_name='estudo',
            name='impostos_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='indice_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='indice_construcao',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Índice de Construção / Solo Criado', max_digits=14),
        ),
        migrations.AddField(
            model_name='estudo',
            name='itbi_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='marketing_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='perc_projetos',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% sobre custo de construção', max_digits=8),
        ),
        migrations.AddField(
            model_name='estudo',
            name='projetos_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='projetos_valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estudo',
            name='receita_final',
            field=models.BooleanField(default=False, help_text='False=Inicial / True=Final'),
        ),
        migrations.AddField(
            model_name='estudo',
            name='terreno_cor_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='terreno_desemb_ck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='terreno_valor_base_itbi',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Base para cálculo do ITBI', max_digits=14),
        ),
        migrations.AddField(
            model_name='estudo',
            name='tx_adm_ck',
            field=models.BooleanField(default=True),
        ),
    ]
