# Generated by Django 6.0.6 on 2026-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidade', '0002_estudo_assistencia_ck_estudo_capital_proprio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudo',
            name='indice_reajuste',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Índice de reajuste', max_digits=10),
        ),
        migrations.AddField(
            model_name='estudo',
            name='valor_cub',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Valor do CUB (R$)', max_digits=14),
        ),
    ]
