# Generated by Django 6.0.6 on 2026-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidade', '0003_estudo_indice_reajuste_estudo_valor_cub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='agrupamento',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
