# Generated by Django 6.0.6 on 2026-06-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidade', '0004_config_agrupamento_inteiro'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE viab_config SET agrupamento = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='config',
            name='agrupamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viabilidade.configagrupamento'),
        ),
    ]
