# Generated by Django 6.0.6 on 2026-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidade', '0005_config_agrupamento_volta_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramvendas',
            name='preco_venda_ref',
            field=models.IntegerField(default=1),
        ),
    ]
