# Generated by Django 5.2.6 on 2026-06-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoMaxFlora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('total_unidades', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Importação Max & Flora',
                'verbose_name_plural': 'Importações Max & Flora',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMaxFlora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euc', models.CharField(max_length=20)),
                ('espaco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('locatario', models.CharField(blank=True, default='', max_length=255)),
                ('area_terreo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_mezanino', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_vendas', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('LOCADO', 'Locado'), ('DISPONIVEL', 'Disponível')], default='DISPONIVEL', max_length=20)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('locado_ate', models.DateField(blank=True, null=True)),
                ('condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iptu_tcrs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='maxflora.importacaomaxflora')),
            ],
            options={
                'verbose_name': 'Unidade Max & Flora',
                'verbose_name_plural': 'Unidades Max & Flora',
                'ordering': ['ordem'],
            },
        ),
    ]
