# Generated by Django 5.2.6 on 2026-05-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='banco_agencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='banco_conta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='banco_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='banco_tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=15, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável'), ('separado', 'Separado(a) Judicialmente')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(blank=True, default='brasileiro(a)', max_length=60, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='regime_bens',
            field=models.CharField(blank=True, choices=[('comunhao_parcial', 'Comunhão Parcial de Bens'), ('comunhao_universal', 'Comunhão Universal de Bens'), ('separacao_total', 'Separação Total de Bens'), ('participacao_final', 'Participação Final nos Aquestos')], max_length=30, verbose_name='Regime de Bens'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representa_pj', to='pessoas.pessoa', verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg_orgao_emissor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Órgão Emissor'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_societario',
            field=models.CharField(blank=True, help_text='Ex: Ltda, S/A, EIRELI, MEI', max_length=60, verbose_name='Tipo Societário'),
        ),
    ]
