# Generated by Django 5.2.6 on 2025-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bliss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=20)),
                ('perc_permuta', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('area_privativa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('area_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('garagem', models.CharField(blank=True, max_length=30, null=True)),
                ('deposito', models.CharField(blank=True, max_length=20, null=True)),
                ('tipologia', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao', models.CharField(max_length=30)),
                ('valor_tabela', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'unidades_bliss',
                'ordering': ['bloco', 'unidade'],
            },
        ),
    ]
