# Generated by Django 5.2.6 on 2026-06-20 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incorporadora', '0017_add_bloco_ordem'),
        ('menu_acesso', '0002_popular_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ícone Bootstrap'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL name'),
        ),
        migrations.CreateModel(
            name='EmpresaMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_itens', to='incorporadora.empresa', verbose_name='Empresa')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='menu_acesso.menuitem', verbose_name='Item de Menu')),
            ],
            options={
                'verbose_name': 'Item de Menu da Empresa',
                'verbose_name_plural': 'Itens de Menu da Empresa',
                'ordering': ['empresa', 'menu_item__app', 'menu_item__navbar', 'menu_item__ordem'],
                'unique_together': {('empresa', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_acesso', to='incorporadora.empresa', verbose_name='Empresa')),
                ('itens', models.ManyToManyField(blank=True, help_text='Subconjunto dos itens habilitados para a empresa.', to='menu_acesso.menuitem', verbose_name='Itens habilitados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário da Empresa',
                'verbose_name_plural': 'Usuários da Empresa',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
