# Generated by Django 5.2.6 on 2026-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_acesso', '0003_remove_menuitem_grupos_remove_menuitem_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='grupo',
            field=models.CharField(blank=True, help_text='Apenas para navbar principal: identifica o dropdown (ex: financeiro, admin)', max_length=50, verbose_name='Grupo/Dropdown'),
        ),
    ]
