# Generated by Django 5.2.6 on 2026-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_acesso', '0005_setar_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='subgrupo',
            field=models.CharField(blank=True, help_text='Apenas para Admin: identifica a seção dentro do dropdown (ex: incorporadora, contratos)', max_length=50, verbose_name='Sub-grupo'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='grupo',
            field=models.CharField(blank=True, help_text='Apenas para navbar principal: identifica o dropdown (ex: gerencial, financeiro, admin)', max_length=50, verbose_name='Grupo/Dropdown'),
        ),
    ]
