# Generated by Django 5.2.6 on 2026-05-27 16:18

import apps.propostas.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incorporadora', '0012_seriepagamento_percentual'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('contrato_elaborado', 'Contrato Elaborado'), ('contratada', 'Contratada')], db_index=True, default='rascunho', max_length=30, verbose_name='Situação')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('numero_contrato', models.CharField(blank=True, max_length=30, verbose_name='Nº Contrato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corretor', models.ForeignKey(limit_choices_to={'is_corretor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_corretor', to='pessoas.pessoa', verbose_name='Corretor')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='incorporadora.empreendimento', verbose_name='Empreendimento')),
                ('imobiliaria', models.ForeignKey(limit_choices_to={'is_imobiliaria': True}, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_imobiliaria', to='pessoas.pessoa', verbose_name='Imobiliária')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='incorporadora.tabelavendas', verbose_name='Tabela de Vendas')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('proponente', 'Proponente'), ('interveniente', 'Interveniente'), ('coobrigado', 'Coobrigado')], max_length=20, verbose_name='Papel')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_proposta', to='pessoas.pessoa', verbose_name='Pessoa')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='propostas.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Participante da Proposta',
                'verbose_name_plural': 'Participantes da Proposta',
                'ordering': ['papel', 'pessoa__nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_renda', 'Comprovante de Renda'), ('extrato_bancario', 'Extrato Bancário'), ('comprovante_residencia', 'Comprovante de Residência'), ('certidao', 'Certidão'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to=apps.propostas.models._upload_documento, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('uploaded_em', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='propostas.participanteproposta', verbose_name='Participante')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='propostas.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Documento da Proposta',
                'verbose_name_plural': 'Documentos da Proposta',
                'ordering': ['participante__pessoa__nome', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='SerieProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('tabela', 'Tabela de Vendas'), ('proposta', 'Proposta')], db_index=True, max_length=10, verbose_name='Origem')),
                ('label', models.CharField(max_length=100, verbose_name='Série')),
                ('tipo', models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='fixa', max_length=10, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor (R$)')),
                ('primeiro_vencimento', models.DateField(blank=True, null=True, verbose_name='1º Vencimento')),
                ('indexador', models.CharField(choices=[('nenhum', 'Nenhum'), ('cub_residencial', 'CUB Residencial'), ('cub_comercial', 'CUB Comercial'), ('incc', 'INCC'), ('igpm', 'IGP-M'), ('ipca', 'IPCA')], default='nenhum', max_length=20, verbose_name='Indexador')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='propostas.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Série da Proposta',
                'verbose_name_plural': 'Séries da Proposta',
                'ordering': ['origem', 'ordem', 'primeiro_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='propostas.proposta', verbose_name='Proposta')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='incorporadora.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Unidade da Proposta',
                'verbose_name_plural': 'Unidades da Proposta',
                'ordering': ['unidade__bloco__nome', 'unidade__numero'],
                'unique_together': {('proposta', 'unidade')},
            },
        ),
    ]
