# Generated by Django 5.2.6 on 2026-05-27 17:53

import django.db.models.deletion
from django.db import migrations, models


ETAPAS_INICIAIS = [
    {'slug': 'rascunho',           'label': 'Rascunho',           'cor': '#6c757d', 'ordem': 0, 'pos_x':   60, 'pos_y': 220},
    {'slug': 'enviada',            'label': 'Enviada',            'cor': '#0d6efd', 'ordem': 1, 'pos_x':  300, 'pos_y': 220},
    {'slug': 'em_analise',         'label': 'Em Análise',         'cor': '#0ea5e9', 'ordem': 2, 'pos_x':  540, 'pos_y': 220},
    {'slug': 'aprovada',           'label': 'Aprovada',           'cor': '#198754', 'ordem': 3, 'pos_x':  540, 'pos_y':  80},
    {'slug': 'reprovada',          'label': 'Reprovada',          'cor': '#dc3545', 'ordem': 4, 'pos_x':  540, 'pos_y': 360},
    {'slug': 'contrato_elaborado', 'label': 'Contrato Elaborado', 'cor': '#6f42c1', 'ordem': 5, 'pos_x':  780, 'pos_y':  80},
    {'slug': 'contratada',         'label': 'Contratada',         'cor': '#0f766e', 'ordem': 6, 'pos_x': 1020, 'pos_y':  80},
]


def seed_etapas(apps, schema_editor):
    WorkflowEtapa = apps.get_model('propostas', 'WorkflowEtapa')
    for e in ETAPAS_INICIAIS:
        WorkflowEtapa.objects.get_or_create(slug=e['slug'], defaults=e)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_workflowconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('label', models.CharField(max_length=100, verbose_name='Nome')),
                ('cor', models.CharField(default='#6c757d', max_length=20, verbose_name='Cor')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pos_x', models.IntegerField(default=100, verbose_name='X')),
                ('pos_y', models.IntegerField(default=100, verbose_name='Y')),
            ],
            options={
                'verbose_name': 'Etapa do Workflow',
                'verbose_name_plural': 'Etapas do Workflow',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='propostas.workflowetapa', verbose_name='De')),
                ('para_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='propostas.workflowetapa', verbose_name='Para')),
            ],
            options={
                'verbose_name': 'Transição do Workflow',
                'verbose_name_plural': 'Transições do Workflow',
                'unique_together': {('de_etapa', 'para_etapa')},
            },
        ),
        migrations.RunPython(seed_etapas, noop),
    ]
