# Generated by Django 5.2.6 on 2026-08-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Importação de Faturamento',
                'verbose_name_plural': 'Importações de Faturamento',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('codigo_centro_custo', models.CharField(blank=True, default='', max_length=20)),
                ('nome_centro_custo', models.CharField(blank=True, default='', max_length=255)),
                ('codigo_cliente', models.CharField(blank=True, default='', max_length=20)),
                ('nome_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('numero_titulo', models.CharField(blank=True, default='', max_length=40)),
                ('numero_parcela', models.CharField(blank=True, default='', max_length=20)),
                ('numero_unidade', models.CharField(blank=True, default='', max_length=40)),
                ('codigo_plano_financeiro', models.CharField(blank=True, default='', max_length=20)),
                ('nome_plano_financeiro', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(choices=[('INCORPORACAO', 'Incorporação'), ('LOCACAO', 'Locações'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('data_baixa', models.DateField()),
                ('valor_baixa', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='faturamento.importacaofaturamento')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'ordering': ['-data_baixa'],
                'indexes': [models.Index(fields=['data_baixa'], name='faturamento_data_ba_2f097e_idx'), models.Index(fields=['categoria'], name='faturamento_categor_cbedd3_idx')],
            },
        ),
    ]
