# Generated by Django 5.2.6 on 2026-08-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Importação de A Receber',
                'verbose_name_plural': 'Importações de A Receber',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.AddField(
            model_name='recebimento',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('numero_titulo', models.CharField(max_length=40)),
                ('nome_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(choices=[('INCORPORACAO', 'Incorporação'), ('LOCACAO', 'Locações'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mes_venda', models.DateField(blank=True, null=True)),
                ('mes_venda_manual', models.DateField(blank=True, help_text='Sobrepõe o mês calculado automaticamente, quando preenchido.', null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-mes_venda'],
                'indexes': [models.Index(fields=['mes_venda'], name='faturamento_mes_ven_b75c6d_idx'), models.Index(fields=['categoria'], name='faturamento_categor_f56e95_idx')],
                'unique_together': {('codigo_empresa', 'numero_titulo')},
            },
        ),
        migrations.CreateModel(
            name='ParcelaPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=40)),
                ('numero_titulo', models.CharField(blank=True, default='', max_length=40)),
                ('numero_parcela', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_condicao', models.CharField(blank=True, default='', max_length=10)),
                ('numero_unidade', models.CharField(blank=True, default='', max_length=40)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='faturamento.importacaoareceber')),
            ],
            options={
                'verbose_name': 'Parcela Pendente',
                'verbose_name_plural': 'Parcelas Pendentes',
                'ordering': ['vencimento'],
                'indexes': [models.Index(fields=['numero_titulo'], name='faturamento_numero__292af3_idx')],
            },
        ),
    ]
