# Generated by Django 5.2.6 on 2026-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_importacaoareceber_recebimento_data_emissao_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo_centro_custo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nome_centro_custo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
