# Generated by Django 5.2.6 on 2025-09-21 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome curto do índice (ex.: IPCA, CDI, etc.)', max_length=40, verbose_name='Descrição')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Diário'), (2, 'Mensal')], default=2, verbose_name='Período')),
                ('calculo', models.PositiveSmallIntegerField(choices=[(1, 'Direto'), (2, 'Acumulado')], default=1, verbose_name='Cálculo')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Anterior'), (2, 'Atual')], default=2, verbose_name='Tipo de referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice',
                'verbose_name_plural': 'Índices',
                'db_table': 'indices',
                'ordering': ['descricao'],
                'indexes': [models.Index(fields=['descricao'], name='indices_descric_552a41_idx'), models.Index(fields=['periodo', 'calculo', 'tipo'], name='indices_periodo_075ae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data de referência do índice (ex.: 2025-09-01)', verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=8, help_text='Valor do índice na data (p.ex.: 0.01023456 = 1,023456%)', max_digits=12, validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000)], verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indice', models.ForeignKey(db_column='id_indice', on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='indices.indice', verbose_name='Índice')),
            ],
            options={
                'verbose_name': 'Valor de Índice',
                'verbose_name_plural': 'Valores de Índice',
                'db_table': 'indices_datas',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['indice', 'data'], name='indices_dat_id_indi_e5cf92_idx'), models.Index(fields=['data'], name='indices_dat_data_643c1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('indice', 'data'), name='uniq_indice_data')],
            },
        ),
    ]
