# Generated by Django 5.2.6 on 2026-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinutaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('avista', 'À Vista'), ('parcelado', 'Parcelado'), ('permuta', 'Permuta'), ('outro', 'Outro')], default='parcelado', max_length=20, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='minutas/', verbose_name='Arquivo (.docx)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minuta de Contrato',
                'verbose_name_plural': 'Minutas de Contrato',
                'ordering': ['nome'],
            },
        ),
    ]
