# Generated by Django 5.2.6 on 2026-05-28 16:40

import apps.contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('propostas', '0003_workflowetapa_workflowtransicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.contratos.models._upload_contrato, verbose_name='Arquivo')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_gerados', to='contratos.minutacontrato', verbose_name='Minuta')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_gerados', to='propostas.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Contrato Gerado',
                'verbose_name_plural': 'Contratos Gerados',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
