# Generated by Django 6.0.5 on 2026-05-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.CharField(blank=True, max_length=20)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('empreendimento', models.CharField(blank=True, max_length=255)),
                ('vgv', models.FloatField(default=0)),
                ('pv', models.FloatField(default=0)),
                ('primeira_parcela', models.DateField()),
                ('ultima_parcela', models.DateField(blank=True, null=True)),
                ('imobiliaria', models.CharField(blank=True, max_length=255)),
                ('corretor', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tabela', 'Tabela de Preços'), ('unidades', 'Unidades'), ('vendas', 'Vendas'), ('fluxo', 'Fluxo de Caixa'), ('vinculo', 'Vínculos'), ('permutas', 'Permutas')], max_length=20)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('nome_arquivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='Permuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=50, unique=True)),
                ('tipologia', models.CharField(blank=True, max_length=100)),
                ('situacao', models.CharField(blank=True, max_length=50)),
                ('area_privativa', models.FloatField(default=0)),
                ('valor_total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('complemento_tipo', models.CharField(blank=True, max_length=100)),
                ('area_privativa', models.FloatField(default=0)),
                ('area_priv_acessoria', models.FloatField(default=0)),
                ('area_comum', models.FloatField(default=0)),
                ('fracao_ideal', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('situacao', models.CharField(blank=True, max_length=50)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('imobiliaria', models.CharField(blank=True, max_length=255)),
                ('m2', models.CharField(blank=True, max_length=20)),
                ('espacos', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=50, unique=True)),
                ('garagens', models.CharField(blank=True, max_length=100)),
                ('hb', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FluxoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_idx', models.SmallIntegerField()),
                ('valor', models.FloatField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cota365.fluxocontrato')),
            ],
            options={
                'ordering': ['mes_idx'],
            },
        ),
    ]
