# Generated by Django 5.2.6 on 2026-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('situacao', models.CharField(blank=True, max_length=100)),
                ('reserva', models.CharField(blank=True, max_length=20)),
                ('corretor', models.CharField(blank=True, max_length=255)),
                ('corretor_apelido', models.CharField(blank=True, max_length=100)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('imobiliaria', models.CharField(blank=True, max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('tipo_unidade', models.CharField(blank=True, max_length=100)),
                ('valor_contrato', models.FloatField(default=0)),
                ('valor_presente', models.FloatField(default=0)),
                ('pct_comissao', models.FloatField(default=0)),
                ('valor_comissao', models.FloatField(default=0)),
                ('pct_premio', models.FloatField(default=0)),
                ('valor_premio', models.FloatField(default=0)),
                ('tipo_comissao', models.CharField(blank=True, max_length=100)),
                ('valor_comissao_pagar', models.FloatField(default=0)),
                ('regra_comissao', models.CharField(blank=True, max_length=100)),
                ('tipo_venda', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
