# Generated by Django 5.2.6 on 2026-05-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0002_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='corretor_apelido',
        ),
        migrations.RemoveField(
            model_name='comissao',
            name='regra_comissao',
        ),
        migrations.RemoveField(
            model_name='comissao',
            name='tipo_venda',
        ),
        migrations.RemoveField(
            model_name='comissao',
            name='valor_presente',
        ),
    ]
