# Generated by Django 5.2.6 on 2026-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0003_remove_comissao_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comissao',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
