# Generated by Django 5.2.6 on 2026-05-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0007_alter_comissao_options_alter_importlog_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('parcela', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(default=0)),
                ('cliente', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['vencimento', 'titulo'],
            },
        ),
    ]
