# Generated by Django 5.2.6 on 2026-05-25 14:17

from django.db import migrations, models


def backfill_valor_original(apps, schema_editor):
    Parcela = apps.get_model('cota365', 'Parcela')
    Parcela.objects.filter(valor_original=0).update(valor_original=models.F('valor'))


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0009_importlog_sha256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissao',
            options={'ordering': ['unidade', 'beneficiario']},
        ),
        migrations.AddField(
            model_name='parcela',
            name='valor_original',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='seriecontrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(backfill_valor_original, migrations.RunPython.noop),
    ]
