# Generated by Django 5.2.6 on 2026-05-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0008_parcela'),
        ('cota365', '0009_importlog_sha256'),
    ]

    operations = [
    ]
