# Generated by Django 5.2.6 on 2026-05-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0010_merge_0008_parcela_0009_importlog_sha256'),
        ('cota365', '0010_parcela_valor_original'),
    ]

    operations = [
    ]
