# Generated by Django 5.2.6 on 2026-05-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0010_parcela_valor_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoObs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.CharField(db_index=True, max_length=20, unique=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Observação de Comissão',
                'verbose_name_plural': 'Observações de Comissões',
            },
        ),
    ]
