# Generated by Django 5.2.6 on 2026-05-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0011_comissaoobs'),
        ('cota365', '0011_merge_20260525_1139'),
    ]

    operations = [
    ]
