# Generated by Django 5.2.6 on 2026-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0015_venda_valor_contrato_data_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimoTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('competencia', models.DateField()),
                ('valor_minimo', models.FloatField()),
                ('unidade', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-competencia', 'tipo'],
                'unique_together': {('tipo', 'competencia')},
            },
        ),
    ]
