# Generated by Django 5.2.6 on 2026-07-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0016_add_minimo_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='obs_pos_venda',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
