# Generated by Django 5.2.6 on 2026-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0017_venda_obs_pos_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='unidade',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
