# Generated by Django 5.2.6 on 2026-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0018_parcela_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(db_index=True, max_length=255)),
                ('data_acesso', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Acesso do Cliente',
                'verbose_name_plural': 'Acessos dos Clientes',
                'ordering': ['-data_acesso'],
            },
        ),
    ]
