# Generated by Django 5.2.6 on 2026-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0019_acessocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='tipo',
            field=models.CharField(choices=[('tabela', 'Tabela de Preços'), ('unidades', 'Unidades'), ('vendas', 'Vendas'), ('fluxo', 'Fluxo de Caixa'), ('vinculo', 'Vínculos'), ('permutas', 'Permutas'), ('series', 'Séries de Contratos'), ('faturamento', 'Faturamento')], db_index=True, max_length=20),
        ),
    ]
