# Generated by Django 5.2.6 on 2026-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0020_alter_importlog_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='tipo',
            field=models.CharField(choices=[('tabela', 'Tabela de Preços'), ('unidades', 'Unidades'), ('vendas', 'Vendas'), ('fluxo', 'Fluxo de Caixa'), ('vinculo', 'Vínculos'), ('permutas', 'Permutas'), ('series', 'Séries de Contratos'), ('faturamento', 'Faturamento'), ('fat_areceber', 'Faturamento (A Receber)')], db_index=True, max_length=20),
        ),
    ]
