# Generated by Django 5.2.6 on 2026-09-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0021_alter_importlog_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tabela', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AT', 'Ato'), ('PM', 'Parcela Mensal'), ('RA', 'Reforço'), ('CH', 'Chaves'), ('FI', 'Financiamento'), ('PE', 'Permuta'), ('OU', 'Outro')], max_length=2)),
                ('periodicidade', models.CharField(choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('primeiro_vencimento', models.DateField()),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Série de Condição',
                'verbose_name_plural': 'Séries de Condição',
                'ordering': ['nome_tabela', 'ordem'],
            },
        ),
        migrations.AlterField(
            model_name='importlog',
            name='tipo',
            field=models.CharField(choices=[('tabela', 'Tabela de Preços'), ('unidades', 'Unidades'), ('vendas', 'Vendas'), ('fluxo', 'Fluxo de Caixa'), ('vinculo', 'Vínculos'), ('permutas', 'Permutas'), ('series', 'Séries de Contratos'), ('faturamento', 'Faturamento'), ('fat_areceber', 'Faturamento (A Receber)'), ('condicao_pagamento', 'Condição de Pagamento')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ValorCondicaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(db_index=True, max_length=50)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=14)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='cota365.seriecondicao')),
            ],
            options={
                'verbose_name': 'Valor de Condição por Unidade',
                'verbose_name_plural': 'Valores de Condição por Unidade',
                'unique_together': {('serie', 'unidade')},
            },
        ),
    ]
