# Generated by Django 5.2.6 on 2026-09-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cota365', '0022_seriecondicao_parcela_valor_original_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriecondicao',
            options={'ordering': ['ordem'], 'verbose_name': 'Série de Condição', 'verbose_name_plural': 'Séries de Condição'},
        ),
        migrations.RemoveField(
            model_name='seriecondicao',
            name='nome_tabela',
        ),
        migrations.AlterField(
            model_name='seriecondicao',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
