# Generated by Django 5.2.6 on 2026-06-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajr_padrao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogador',
        ),
    ]
